### ISSUE TITLE
Update for NL V2.0.X

### ISSUE THREAD

**Issue by IkiaeM** [GIGABAIT-Official/TemplateSwitch#1]
Update for NL V2.0.X

**Comment by aidanarredondo** [comment]
> Update for NL V2.0.X

Though Im not the dev, Im trying to update it for my site due to an issue with the profile template. 
All users can choose a template of choice in there profile settings as long as that template is active. So that being said i don't think they will update this as there is really no point but Im working to get it to work on the latest version of nameless.

**Comment by IkiaeM** [comment]
Please feel free to share your update, I would surely be interested to see what it brings.
Thanks for your answer

**Comment by PadowYT2** [comment]
Is this really needed? Well as it is used for view websites, but alright I will try my best after commits to NamelessMC

**Comment by aidanarredondo** [comment]
I was only trying to update it as all users on my site cant chose a template via profile settings atm. Im working to fix it, but i was going to try to update this to implement on my site untill i fix the user settings issue on my site and so i can just see if any user can chose a template or if its just my site not allowing users to chose a template of choice no mater the method.

**Comment by PadowYT2** [comment]
![https://cdn.discordapp.com/attachments/996898255654891550/1027543989865414666/unknown.png](https://cdn.discordapp.com/attachments/996898255654891550/1027543989865414666/unknown.png)
